name:                json-to-yaml
version:             0.1.0.0
github:              "akashche/json-to-yaml"
license:             BSD3
author:              "akashche"
maintainer:          "akashche@redhat.com"
copyright:           "2018 akashche at redhat.com"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/akashche/json-to-yaml#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- parsec
- text
- vector

library:
  source-dirs: src

executables:
  json-to-yaml-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - json-to-yaml

tests:
  json-to-yaml-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - json-to-yaml
    - directory
